import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import Header from '@/components/Header';

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create Next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} antialiased bg-black p-4 px-16`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
